server:
  port: 8085
  servlet:
    context-path: /api/v1

spring:
  application:
    name: document-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/ImmigraSync_documents}
    username: postgres
    # Uses environment variable DB_PASSWORD if set, otherwise defaults to 'password'
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hikari:
          initialization-fail-timeout: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL: DEBUG