server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    # Essential: Stop the Eureka Server from trying to act as a client
    register-with-eureka: false
    # Essential: Stop the Eureka Server from trying to fetch registry from others
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/