server:
  port: 8081

spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ImmigraSync_authentication
    username: postgres
    password: henry
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: dGhpcy1pcy1hLXN1cGVyLXNlY3JldC1rZXktdGhhdC1pcy1hdC1sZWFzdC0yNTYtYml0cy1sb25nLWZvci1qd3Qtc2lnbmluZw==
  expiration: 86400000

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.codequest.authenticationservice: DEBUG